-- return {
--   "mrcjkb/rustaceanvim",
--   version = "^5",
--   lazy = false,
--   ft = { "rust" },
--   ["rust-analyzer"] = {
--     cargo = {
--       allFeatures = true
--     }
--   }
--
-- }
--
return {}
